services:
  - type: web
    name: wheelter
    env: node
    plan: starter
    buildCommand: yarn --frozen-lockfile --prod=false &&
      blitz build &&
      blitz prisma migrate deploy --preview-feature
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: wheelter-db
          property: connectionString

databases:
  - name: wheelter-db
    plan: starter
